README.md
=> docs: update the introduction in README

website/docusaurus.config.js, website/package.json, website/yarn.lock
Add the Google Analytics 4 
Resolved #556 
- Add **GTag**
- Add **Discord** channel
- Upgrade the Docusaurus to` 2.0.0-beta.13`
=> docs: add Google Analytics 4 to website

src/components/display/__tests__/__snapshots__/display.test.tsx.snap, src/components/display/__tests__/display.test.tsx, src/components/display/index.tsx, src/components/index.ts, src/controller/__tests__/activityBar.test.ts, src/provider/__tests__/__snapshots__/molecule.test.tsx.snap, src/workbench/__tests__/__snapshots__/workbench.test.tsx.snap, src/workbench/__tests__/workbench.test.tsx, src/workbench/menuBar/style.scss, src/workbench/style.scss, src/workbench/workbench.tsx
Use css to control the display and hiding of modules under workbench.
Optimize the style of MenuBar in horizontal mode.
Fixes #562 
- Added the Display component.
- The module that originally used conditional rendering under the workbench was changed to use the Display component to wrap.
- Adjusted the height and font size of MenuBar in horizontal mode.
=> feat: use css to control the display and hiding of modules under workbench 

website/docs/advanced/customize-workbench.md, website/docs/guides/extend-workbench.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/advanced/customize-workbench.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-workbench.md
Update relevant documents of MenuBar
-   Add description of MenuBar layout mode
-   Update the workbench source code in customize-workbench.md
=> docs: update relevant documents of MenuBar

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
- update the issue templates
Closed #572
=> chore: update issue templates

src/components/input/style.scss, src/components/select/style.scss, src/workbench/sidebar/explore/style.scss, src/workbench/style.scss
Correct the style of input and select
Fixes #563
=> fix: correct the style of input and select

website/docs/guides/extend-workbench.md
=> docs: translate extend-workbench

website/docs/advanced/customize-workbench.md, website/docs/guides/extend-builtin-ui.md, website/docs/guides/extend-color-theme.md, website/docs/guides/extend-keybinding.md, website/docs/guides/extend-locales.md, website/docs/guides/extend-quick-access.md, website/docs/guides/extend-settings.md, website/docs/guides/extend-workbench.md, website/docs/guides/extension.md, website/docs/guides/icons.md, website/docs/overview.md, website/docs/quick-start.md, website/docs/the-first-extension.md
Translate the docs in English
Fixes #546
=> docs: translate the docs in English

website/docusaurus.config.js
Set the locale as English by default
=> docs: set the locale as English by default

website/docs/guides/extend-locales.md, website/docs/overview.md, website/docusaurus.config.js, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-locales.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/overview.md
Add notes about Korean language support.
Update editUrl configuration.
=> docs: add notes about Korean language support

website/docusaurus.config.js
Add Algolia DocSearch to website
=> docs: add Algolia DocSearch to website

website/docusaurus.config.js
Add contextualSearch configuration
=> docs: add contextualSearch configuration

src/workbench/menuBar/style.scss
Increase the z-index value of SubMenu in horizontal mode.
Fixes #586
=> fix: increase the z-index value of SubMenu in horizontal mode

website/docs/guides/extend-builtin-ui.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-builtin-ui.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/guides/extend-builtin-ui.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.2/guides/extend-builtin-ui.md, website/versioned_docs/version-0.9.0-beta.1/guides/extend-builtin-ui.md, website/versioned_docs/version-0.9.0-beta.2/guides/extend-builtin-ui.md
- improve the link about search Service in [search](https://dtstack.github.io/molecule/docs/guides/extend-builtin-ui#search)
=> docs: improve the link about Search Service

README-koKR.md, README-zhCN.md, README.md, website/docs/introduction.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md
Add the online chat info
-   Add Discord in README
-   Add Discord to the website
=> docs: add the chat entry of Discord

src/controller/menuBar.ts, src/model/workbench/menuBar.ts, src/services/workbench/layoutService.ts, stories/extensions/test/testPane.tsx
Fix the problem that the MenuBar mode status is out of sync.
Fixes #626 
-   Use event subscription to update menuBar data
-   Add a case of modifying the MenuBar mode in TestPanel
=> fix: sync menuBar mode status

src/i18n/localeService.ts, src/provider/molecule.tsx
Let the defaultLocale property of MoleculeProvider work.
Fixes #615
=> fix: let the defaultLocale property of MoleculeProvider work.

src/workbench/menuBar/__tests__/menubar.test.tsx, src/workbench/menuBar/horizontalView.tsx
修复了在 [Taiga](https://github.com/DTStack/Taiga) 中点击 MenuBar 的菜单项并关闭了菜单后，再 hover 菜单项时仍会自动展示菜单的问题。
-   Optimized the interaction logic of MenuBar in horizontal mode.
=> fix: the interaction bug of MenuBar in horizontal mode

src/services/workbench/editorService.ts
=> fix: update explorer when closing editor tab

src/workbench/notification/style.scss
Improve the style of the Button in Notification.
=> fix: improve the style of the Button in Notification

src/workbench/sidebar/explore/editorTree.tsx, src/workbench/sidebar/explore/style.scss
Add icons to EditorTree and optimize its style
Fixes #531
=> fix: add icons to EditorTree and optimize its style

src/components/scrollable/style.scss, src/workbench/editor/welcome/style.scss
1.Hide the native scrollbar in Scrollable component.
2.Improve the style of the Welcome page.
Fixes #588 #589
=> fix: improve the style of scrollbar in Scrollable component

src/components/button/__tests__/__snapshots__/button.test.tsx.snap, src/components/button/index.tsx, src/components/button/style.scss, src/components/dialog/__tests__/__snapshots__/actionbutton.test.tsx.snap, src/provider/__tests__/__snapshots__/molecule.test.tsx.snap, src/services/theme/colorRegistry.ts, src/services/theme/helper.ts, src/workbench/notification/__tests__/__snapshots__/localeNotification.test.tsx.snap, src/workbench/sidebar/__tests__/folderTree.test.tsx, stories/components/17-Dialog.stories.tsx
- 重构 Button 组件
- 用 button 标签代替 a 标签，更语义化
- 优化 button 的样式
- 优化 button.hoverBackground 的取值。除非 theme 中声明了一个固定值，否则该值通过获取 button.background 的颜色再处理
- 移除测试用例中没有用的属性
=> refactor: replace the A tag by button tag in Button component

src/controller/notification.tsx, src/workbench/notification/__tests__/notificationPane.test.tsx, src/workbench/notification/notificationPane/index.tsx
=> Revert "fix: prevent the  contextmenu event of Notification"

package.json, website/docs/advanced/customize-workbench.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/advanced/customize-workbench.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/advanced/customize-workbench.md, yarn.lock
移除无用的 react-split-pane 依赖
- 移除 react-split-pane 从 package.json 和 yarn.lock
- 移除文档中 react-split-pane 相关内容
=> chore: remove react split pane

src/components/collapse/index.tsx, src/components/split/SplitPane.tsx
=> fix: fix usage of useMemo

.github/workflows/deploy.yml, .github/workflows/test-deploy.yml
更新gh-pages自动部署配置，修复部署时缺少依赖的问题。
-   在website打包之前增加对外部依赖包的安装
=> ci: update gh-pages deployment action

src/extensions/github-plus-theme-master/themes/github-plus-theme.json, src/services/theme/helper.ts
=> fix: compatible background color for buttons and menu items

src/components/tabs/__tests__/__snapshots__/tabs.test.tsx.snap, src/components/tabs/__tests__/tabExtra.test.tsx, src/components/tabs/__tests__/tabs.test.tsx, src/components/tabs/style.scss, src/components/tabs/tab.tsx, src/components/tabs/tabExtra.tsx, stories/extensions/test/testPane.tsx
- 修复 tab 在某些情况下样式移位的问题
- 优化 tabExtra 组件的 DOM 结构
- 优化样式
Closed #731
=> fix(editor): fix styles in editor tab extra

src/components/breadcrumb/__tests__/__snapshots__/breadcrumb.test.tsx.snap, src/components/breadcrumb/__tests__/breadcrumb.test.tsx, src/components/breadcrumb/index.tsx, src/components/breadcrumb/style.scss
- 修复 breadcrumbs 组件丢失主题色的问题
- 添加 color 和 background 
- 添加 focus 的颜色
Closed #715
=> fix(components): add color variables for breadcrumb

.github/workflows/main.yml, package.json
Adding a new `yarn web` stage in the `build` job.
Fixes #688 
-   Adding the `yarn web` stage to prevent the built files can't work correctly.
=> ci: add yarn web stage

package.json
=> chore: update react version of peerDependencies

src/components/tabs/tab.tsx
=> fix: remove findDOMNode usage

src/common/css.ts, src/components/dialog/style.scss
=> chore: remove todo comments

src/components/dialog/confirm.tsx
=> fix: remove todos

src/workbench/sidebar/explore/folderTree.tsx
Declare the `useEffect` hook before the return statement
Fixes #806 
Refer to https://github.com/facebook/react/issues/24391#issuecomment-1106410214
=> fix: declare the useEffect before return

src/components/breadcrumb/style.scss
- 优化面包屑组件的样式，修复换行的问题
Closed #811
=> fix: improve breadcrumb

app/src/components/testPane.tsx, pnpm-lock.yaml, src/client/components/notification/index.scss, src/client/components/notification/index.tsx, src/client/components/notification/localeNotification.tsx, src/client/components/notification/notificationPanel.tsx, src/controllers/index.ts, src/controllers/notification.tsx, src/extensions/index.ts, src/extensions/locales/en.json, src/extensions/locales/zh-CN.json, src/extensions/notification/index.ts, src/models/builtin.ts, src/models/locale.ts, src/models/notification.ts, src/services/action.ts, src/services/extension.ts, src/services/instance.ts, src/services/notification.ts, src/types.ts
=> feat: migrate notification

app/vite.config.ts, package.json, pnpm-lock.yaml, src/client/hooks/useSettings.ts, src/client/slots/editor/index.tsx, src/const/options.ts, src/controllers/editor.ts, src/controllers/index.ts, src/controllers/settings.ts, src/extensions/actions/index.ts, src/extensions/actions/quickAccessSettingsAction.ts, src/extensions/actions/quickSelectThemeAction.ts, src/extensions/index.ts, src/extensions/settings/index.ts, src/models/builtin.ts, src/models/editor.ts, src/models/setting.ts, src/services/action.ts, src/services/editor.ts, src/services/extension.ts, src/services/instance.ts, src/services/layout.ts, src/services/setting.ts, src/types.ts, src/utils/index.ts
=> feat: support settings service

app/src/components/testPane.tsx, pnpm-lock.yaml, src/controllers/menuBar.ts, src/extensions/actions/index.ts, src/extensions/actions/quickAccessCommandAction.ts, src/extensions/menuBar/index.tsx, src/models/menuBar.ts, src/services/extension.ts, src/services/layout.ts, src/services/menuBar.ts, src/types.ts
menuBar基础完善
- 菜单中添加切换activityBar、命令面板功能
- 移除无用代码及代码中的非空断言操作符
- testPane中添加打开文件示例
- extensions的activate方法时添加monaco传参，以满足在extensions中调用monaco的api
- 菜单中的新建文件、打开、撤销、重做等功能
- 打开命令面板功能，provider 待迁移（或者其他方式实现）
=> feat: improve the basic functions of menuBar

app/src/extensions/testPane.tsx, src/client/slots/panel/index.scss, src/extensions/panel/index.tsx
完善panel的基础功能和样式
- panel 交互及样式保持和1.x一致
- 支持通过 contextMenu 来隐藏自定义的 panelItem
- output 单独去做
- panelItem 添加后的自动滚动功能，可以和editor tab以及editorTree、folderTree一起做
=> feat: improve basic functions and styles of the panel

.github/workflows/main.yml, CHANGELOG.md
=> chore: update codecov-action

app/src/App.tsx, src/extensions/themes/index.ts, src/services/colorTheme.ts, src/services/instance.ts
- 支持触发colorTheme的onChange事件
- 支持设置默认主题 
- 将colorTheme持久化功能内置
=> feat(colorTheme): support to set default colorTheme
