DTStack/molecule

src/controller/menuBar.ts, src/workbench/style.scss, src/workbench/workbench.tsx
- 修复当 StatusBar 隐藏时的布局问题
- 修复 ActivityBar 的右键菜单中 Menu 项的勾选状态问题
- 当隐藏 StatusBar 时更新布局样式
- 点击 MenuBar 中的 Show Menu Bar 时，增加对 ActivityBar 右键菜单状态的更新
=> fix: re-layout the Workbench when StatusBar is hidden

src/model/index.ts, src/molecule.api.ts, src/monaco/api.ts, src/monaco/index.ts, website/sidebars.js
导出 Keybinding， QuickAccess 相关类型文件
Fixes #532 
-  导出 `monaco`/common 中的相关文件
- 导出 `KeyChord, IQuickAccessService`
- 导出 **keybinding** `model` 相关类型声明
=> feat: provide types of Keybinding and QuickAccess

src/provider/__tests__/molecule.test.tsx, src/provider/molecule.tsx, src/services/__tests__/extensionService.test.ts, src/services/extensionService.ts
Disable to reload the `initialize` method of `MoleculeProvider` when triggering the Componen hot reload.
Fixes #579 
-   Add `loaded` flag in `ExtensionService`
-   Not allowed to load the `initialize` if the `ExtensionService` is loaded
-  Add unit tests for **loaded** logic
=> fix: not allowed to reload the initialize method 

website/docs/overview.md, website/docs/quick-start.md, website/docs/the-first-extension.md
translate two parts of documents to English
Fixes # (issue)
OverView and Quick-Start have been translated to English.
-   Change A
-   Change B
=> docs: translate Overview, QuickStart to English

website/docusaurus.config.js
Remove the external properties and methods in API docs.
Fixes #606
=> docs: remove the external properties and methods in API docs

src/common/__tests__/dom.test.ts, src/provider/__tests__/__snapshots__/molecule.test.tsx.snap, src/workbench/activityBar/__tests__/activityBarItem.test.tsx, src/workbench/activityBar/activityBarItem.tsx
Fix the style of the context menu of ActivityBarItem.
Fixes #577 
-   Replace DropDown with contextView to display ActivityBarItem's context menu.
=> fix: the style of the context menu of ActivityBarItem

src/model/workbench/explorer/folderTree.tsx, src/services/workbench/__tests__/folderTreeService.test.ts, src/services/workbench/explorer/folderTreeService.ts, website/docs/guides/extend-builtin-ui.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-builtin-ui.md
FolderTree's sorting function changed to configurable.
FolderTree.update supports updating the node whose id is 0.
Fixes #582
Fixes #604  
-   Add the autoSort property to control whether to sort, and the default value is false.
-   Add the toggleAutoSort method to toggle the value of autoSort.
-   The update method supports updating the node whose id is 0.
=> feat: support to set the folderTree nodes whether to sort by default

src/extensions/folderTree/index.tsx, stories/extensions/test/index.tsx, website/docs/guides/extend-builtin-ui.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-builtin-ui.md
Move the node removal logic from the built-in FolderTree extension to the test extension.
Fixes #583
=> feat: remove the onRemove processing logic in the built-in FolderTree extension

src/workbench/menuBar/__tests__/menubar.test.tsx, src/workbench/menuBar/horizontalView.tsx, src/workbench/menuBar/menuBar.tsx
Optimize the interaction of MenuBar in horizontal mode
Fixes #625 
-   For the MenuBar in horizontal mode, extract the HorizontalView component.
-   Change the interaction of MenuBar in horizontal mode to be similar to VSCode.
-   Add unit test code.
=> feat: optimize the interaction of MenuBar in horizontal mode

src/common/event/__tests__/eventEmitter.test.ts, src/common/event/eventBus.ts, src/common/event/eventEmitter.ts, src/components/menu/style.scss, src/react/__tests__/connector.test.tsx, src/react/component.ts, src/react/connector.tsx, stories/components/17-Dialog.stories.tsx, stories/extensions/extend-panel/index.tsx, stories/extensions/extend-panel/pane.tsx, stories/extensions/index.ts
修复 `connect` Service 多次后，组件销毁后，导致事件无效的问题
Fixes #596  
-   `EventEmitter` 支持通过事件 `name` 和 `callback` 函数引用取消订阅
-   `connect` **HOC** 组件，按 `callback` 取消事件订阅
-   [x] 增加 connect 组件测试用例
-   [x] 增加 EventEmitter 测试用例
-   [x] 在 Panel 增加 connect 的测试场景
=> fix: Connect component supports to unsubscribe event by pass the callback

src/controller/__tests__/menuBar.test.ts, src/controller/menuBar.ts, src/react/connector.tsx
过滤无用的控制器属性，仅仅保留**事件**方法，**公共属性**
Fixes #634 
-   Connector 增加 `getObjectPublicProperties` 过滤方法
-   Connector 修改继承 Controller 属性的方法
=> refactor(connector): filter the useless properties of Controller

src/common/__tests__/utils.test.ts, src/common/utils.ts, src/model/colorTheme.ts, src/services/__tests__/colorThemeService.test.ts, src/services/theme/colorThemeService.ts
Support to get the mode(dark or light) of the current color theme.
Fixes #627 
-   Added getColorThemeMode method to ColorThemeService class.
-   Added colorLightOrDark utility function.
=> feat: support to get the mode(dark or light) of the current color theme

src/workbench/notification/__tests__/__snapshots__/localeNotification.test.tsx.snap, src/workbench/notification/__tests__/localeNotification.test.tsx, src/workbench/notification/notificationPane/localeNotification.tsx
LocaleNotification supports to trigger reload by pressing the Enter key.
Fixes #616 
-   LocaleNotification supports to trigger reload by pressing the Enter key.
-   Optimize the style and layout of LocaleNotification.
=> feat: LocaleNotification supports to trigger reload by pressing the Enter key

src/components/tabs/tab.tsx, src/components/tabs/tabExtra.tsx, src/controller/panel.tsx
- 修复 panel 关闭后无法自动选择下一个 panel 的问题
- 优化 `onTabChange` 事件
- 无法自动选择的原因是在点击 close 图标的时候，同时触发了 `onClose` 和 `onTabChange` 两个事件，两个事件都修改了 current 的值，按照冒泡的时间顺序，先触发 `onClose` 的 current 修改，然后是 `onTabChange` 的 current 修改，导致 bug。只需要取消 `onClose` 事件的冒泡即可
=> fix: fix panels didn't active the next one after closing automatically

src/components/menu/menu.tsx
Fix the issue that the onClick property of MenuItem will be overridden by custom data.
=> fix: the context menu does not close when the context menu item is clicked.

src/controller/__tests__/menuBar.test.ts, src/controller/menuBar.ts, src/model/workbench/menuBar.ts, src/services/builtinService/const.ts
Fix the issue that the custom menu data is lost when the mode of MenuBar is modified.
-    Modified the logic of updating MenuBar data when modifying the MenuBar mode
=> fix: customized MenuBar data will be lost when modifying the MenuBar's mode

src/workbench/sidebar/explore/style.scss
Improve the style of the EditorTree node's icon
=> fix: improve the style of the EditorTree node's icon

src/extensions/__tests__/folderTree.test.tsx, src/extensions/folderTree/index.tsx, src/model/workbench/editor.ts
Fix filename missing and file path in EditorTree is not updated.
Fixes #658 
-   Improve the logic of updating file name in ExtendsFolderTree
=> fix: filename missing and file path in EditorTree is not updated

.github/workflows/deploy.yml, .github/workflows/test-deploy.yml, package.json
Add **deployment** action for `gh-pages`, it refers to the below document:
https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions
-  Add `deploy.yml` for deployment `gh-pages` when website content changed
-  Add `test-deploy.yml` to test the build of website content
=> ci: add  action for github page  deployment

src/components/tree/index.tsx, src/controller/__tests__/folderTree.test.ts, src/controller/explorer/folderTree.tsx, src/extensions/folderTree/index.tsx, src/model/workbench/explorer/folderTree.tsx, src/services/workbench/__tests__/folderTreeService.test.ts, src/services/workbench/explorer/folderTreeService.ts, src/workbench/sidebar/explore/folderTree.tsx
- folderTree 支持设置 expandKeys
- folderTreeModel 支持 expandKeys
- folderTreeService 支持 set 和 get 方法，同时抛出 onExpandKeys 方法
- folderTreeController 支持 onExpandKeys，支持 emit expand 事件
=> feat: support to set the expandKeys

stories/extensions/test/testPane.tsx
Improve usage examples in TestPane.
Fixes #591 
-   Improve the style of TestPane.
-   Improve the logic of some operations.
-   Improve some display names and content.
-   Add more usage examples.
-   Use Notification to show the results of operations that cannot see changes on the page directly.
=> feat: Improve usage examples in TestPane

src/controller/notification.tsx, src/workbench/notification/__tests__/notificationPane.test.tsx, src/workbench/notification/notificationPane/index.tsx
Add a listener function for the contextmenu event in the NotificationPane component to prevent the bubbling of the native contextmenu event.
Fixes #666
=> fix: prevent the  contextmenu event of Notification

src/components/tree/index.tsx, src/controller/__tests__/explorer.test.ts, src/controller/explorer/explorer.tsx, src/model/workbench/explorer/explorer.tsx, src/services/__tests__/explorerService.test.ts, src/services/builtinService/const.ts, src/services/workbench/explorer/explorerService.ts, stories/extensions/test/index.tsx
- 支持 explorer 通过新特性 #664 收起全部文件夹
- explorer 支持 onCollapseAllFolders 事件
- 修复 Tree 组件的 bug
> 注：用户需要去实现 onCollapseAllFolders 事件，molecule 不负责实现
=> feat: support listen to onCollapseAllFolders

src/common/__tests__/dom.test.ts, src/common/__tests__/utils.test.ts, src/provider/molecule.tsx, src/services/workbench/layoutService.ts
修复重载Molecule后Keybinding功能失效问题。
`说明：Keybinding功能之所以会失效，是因为Molecule重载后重新渲染了dom，导致原先注册并绑定到dom上的监听事件丢失了。`
Fixes #612 
-   每次加载MoleculeProvider时都执行一次monacoService的初始化，以确保能将Keybinding事件绑定到dom上。
-   layoutService中的container改为每次都去查找最新的dom，以确保初始化monacoService时拿到的是最新的dom。
=> fix: make Keybinding work after reloading Molecule

src/components/collapse/index.tsx
修改 Icon，Toolbar 组件在 Collapse 中的引用位置。
从 index 引入会造成循环引用的问题，造成不可预知的 Bug.
-   修改为相对路径的引用
=> fix: import Icon, Toolbar from relative path

src/controller/__tests__/editor.test.ts, src/controller/editor.tsx
修复切换editor tab时，光标不会自动回到上次编辑位置的问题。
-   在编辑器失去焦点时，保存当前的viewState
-   EditorController的initEditorEvents方法由private改为public，并增加了getViewState方法
=> fix: enable the editor to save viewState

src/workbench/editor/group.tsx
修复切换editor tab时editor总是会初始化的问题。
Fixes #663 
-   去掉传给MonacoEditor的key属性（因为切换tab时会导致key变化，从而导致初始化）
=> fix: prevent the editor from initializing when switching tabs

.github/workflows/deploy.yml, .github/workflows/test-deploy.yml, website/docs/advanced/customize-workbench.md, website/docs/guides/extend-keybinding.md, website/docs/guides/extend-quick-access.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/advanced/customize-workbench.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-keybinding.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-quick-access.md
更新自定义工作台文档
-   更新文档中workbench的代码，并去掉了自定义MenuBar部分的介绍
-   更新Action2的引用代码
=> docs: update customize workbench

src/controller/__tests__/problems.test.ts, src/controller/problems.tsx, src/model/problems.tsx, src/services/problemsService.ts, src/workbench/problems/paneView/index.tsx
The tree in Problems panel supports onSelect event.
Fixes #413 
-   Added onSelect function to ProblemsController and ProblemsService
=> feat: the tree in Problems panel supports onSelect event

build/gulpfile.js
- 修复 windows 下运行 web 命令失败的问题
- 原因是因为执行 `build:esm` 后，在 windows 下路径分割符是 `\`， 'mo/common/xxx'  路径会转化成 '..\..\..\common/xxx' 这种路径，而 '\' 是转译的，导致出现问题
Actually:
`windows` 下的 `esm/workbench/editor/welcome/index.js` 文件内容中部分如下：
Expected:
```js
import { prefixClaName } from './../../../common/className';
```
Closed #718
=> fix: yarn web failed in windows

packages/ide/src/services/extensionService.ts
Throws the full Error message when the Extension load exception
Fixes #710 
-   Append the **Exception** object `e` in the ExtensionService `load()` method
=> fix: throws the full Error message when the Extension load exception

src/model/keybinding.ts
an extra empty string was split due to \ufe0e
Fixes #721
```
// old
'↩︎'.split('') // ['↩', '︎'] \u21a9\ufe0e
// new
'↩'.split('') // ['↩'] \u21a9
```
=> fix: use the enter character \u21a9

src/workbench/editor/__tests__/action.test.tsx, src/workbench/editor/action.tsx
The disable button can also trigger events
Fixes #725
Add disable restrictions
=> fix: disable click event when action is disabled

src/workbench/panel/panel.tsx
In Firefox, sort is different from other browsers
Fixes #722
return 0, leaving the position unchanged
1. use firefox
1. change panal
=> fix: change sort default value 0 to be compatible with Firefox (#722)

src/workbench/editor/style.scss
Add a tab.hoverBackground variable to control group tabs Floating background color
Fixes # 716
https://user-images.githubusercontent.com/46592356/170231008-24940ddd-55f6-4222-9020-c07a14cfda8f.mov
-   [ ] add tab.hoverBackground to the thmem configuration file
=> fix: add hover style to tab within group (#716)

src/controller/editor.tsx, src/services/workbench/__tests__/editorService.test.tsx, src/services/workbench/editorService.ts
Can't update editor's value via the updateTab method
Fixes #714
-   `editorInstance.onDidChangeModelContent` added comparisons are made through URIs to limit changes to different editors。This is because when you change the contents of the editor with setValue, the onDidChangeModelContent event is triggered, and leaving it unchecked will cause the updateTab method to be called in onDidChangeModelContent, causing a circular call
-   In the updateTab method, check if tab.data.value exists, and call setGroupEditorValue to update the editor text
-   [ ] use updateTab method
```
const handleSubmit = () => {
molecule.editor.updateTab({
id: current.tab.id,
// update the editor's value by str
data: Object.assign(current.tab.data,{value: str})
})
}
```
-   [ ] View changes in editor text content
- …
=> fix: update tab set value

src/extensions/folderTree/index.tsx, src/services/workbench/__tests__/folderTreeService.test.ts, src/services/workbench/explorer/folderTreeService.ts, stories/extensions/test/testPane.tsx
there is a easier way to get the current treeNode's parentNode?
Fixes #723 
Please describe the changes, help the reviewer to read your code.
-   add getParentNode interface for folderTreeService
-   add Unit test for folderTreeService.getParentNode
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
=> feat: add getParentNode interface for folderTreeService

src/components/collapse/__tests__/index.test.tsx, src/components/collapse/index.tsx, src/model/workbench/explorer/explorer.tsx, src/services/__tests__/explorerService.test.ts, src/services/workbench/explorer/explorerService.ts, src/workbench/sidebar/explore/explore.tsx, stories/extensions/test/testPane.tsx
support to set the expanded panels of Explorer
Fixes #726 
Please describe the changes, help the reviewer to read your code.
-   support to set the expanded panels of Explorer
-   Collapse component support expand activeKeys
-   add  Explorer setExpandedPanels testcase
-   add  Collapse component activePanelKeys attribute testcase
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
=> support to set the expanded panels of Explorer

src/components/tabs/tab.tsx, src/workbench/editor/__tests__/group.test.tsx, src/workbench/editor/editor.tsx, src/workbench/editor/group.tsx, stories/extensions/test/testPane.tsx
exposing more props to renderPane for EditorTab
Fixes #649
-   tab.renderPane method arguments add tab and group
-   add renderPane example
-   [x] I have commented my code, particularly in hard-to-understand areas
=> feat:Exposing more props to renderPane for EditorTab

src/services/instanceService.tsx
- 修复 render 方法会调用多次，导致页面出现重复数据的问题
本地无法复现的原因可能是 react 还是 16.x 的版本导致的，后面需要升级本地的 react 版本。这里的问题是因为 ` const App = () => moInstance.render(<Workbench />);` 如上代码， App 组件因为某种原因重渲染，导致多次执行 moInstance.render 函数
Closed #767 
- 这个问题不论是 yarn web 还是本地的 start 命令启动都无法复现，估计是本地 react 版本问题，后续在做 #688 的时候想办法解决这个问题
=> fix: prevent multiply calls of render function

package.json, scripts/release.mjs
- improve release script 
Closed #769
=> ci: improve release script

src/components/tree/style.scss
Text too long, out of width
Fixes #743 
Text out of width, showing ellipsis
-   [ ] My changes generate no new warnings
=> feat: the text of the optimized tree item is too long

src/services/workbench/explorer/folderTreeService.ts
移除 Safari 中不支持的正则，具体参考：
Fixes #776 
-   移除反向肯定预查条件
=> fix: remove invalid Regex in Safari

src/services/workbench/editorService.ts
- 修复 updateTab 不会修改 current 索引的问题，这不符合 immutable
Closed #732
=> fix: updateTab will change the reference of current tab

src/services/workbench/editorService.ts
- fix set entry failed at some situations
It's a typeScript problem indeed. The `React.ReactNode` is different from `JSX.Element`. This function should have used like 
```js
// correct use
molecule.editor.setEntry(<YourComponent />)
```
rather then 
```js
// wrong use
import YourComponent from '../somewhere';
molecule.editor.setEntry(YourComponent)`
```
but TypeScript will not get a error in wrong usage as the wrong type defined.
Closed #760
=> fix: fix set entry failed at some situations

src/services/workbench/__tests__/editorService.test.tsx, src/services/workbench/editorService.ts
- 修复在某些情况下 updateTab 会更新错误 tab 的内容
- 当存在非编辑器 tab 的时候，该 tab 调用 updateTab，会导致更新 editorInstance 的内容，从而导致更新错误 tab 的内容
Closed #780
=> fix: prevent updateTab with renderPanel tab

scripts/release.mjs
=> ci: update release

.prettierignore, README-koKR.md, README-zhCN.md, README.md, website/docs/introduction.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md
Add [OpenSSF](https://bestpractices.coreinfrastructure.org/zh-CN) best practice badge.
-  add `OpenSSF` badge in README
- add `OpenSSF` badge in Introduction
=> docs:  add OpenSSF best practice badge

src/workbench/sidebar/__tests__/folderTree.test.tsx, src/workbench/sidebar/explore/folderTree.tsx, src/workbench/sidebar/explore/style.scss
- 修复当编辑状态下仍触发 loadData 的问题
- 优化 Input 的样式
=> fix: prevent call loadData when editing

src/components/tabs/index.tsx, src/model/workbench/editor.ts
=> fix: remove useless generic type

src/controller/menuBar.ts
- 移除不必要的注释
对该注释内容做如下解释
1. 默认事件渲染两次，无法复现
2. 我们没有必要去探知用户是否执行，换个角度想，其实 subscribe 和 emit 的机制就是单方面的通知。
3. 推测第一条是为了防止同一个事件，Molecule 执行，用户也定义执行，导致执行两次。这种情况除了这里存在，其他地方也存在。用户应该规避这种情况的出现。
=> chore: remove todos

src/components/tree/__tests__/tree.test.tsx, src/components/tree/index.tsx, src/controller/explorer/folderTree.tsx, src/model/workbench/explorer/folderTree.tsx, src/services/workbench/__tests__/folderTreeService.test.tsx, src/services/workbench/explorer/folderTreeService.ts, src/workbench/sidebar/explore/folderTree.tsx
- 修复 reset 执行后 loadedKeys 的缓存仍然有效的问题
新增 loadedKeys 字段，用于对已加载过的 keys 做受控，在删除和重置的时候会去修改该字段的值
#802
=> feat: define loadedKey to be controlled

src/services/__tests__/panelService.test.ts, src/services/workbench/panelService.ts
- 修复面板切换在某些情况下会报错导致无法切换的问题
- 出现问题的是地方是深拷贝的时候，需要跳过 StandaloneEditor 类。本来是通过 constructor.name 来判断，但是在 terser 之后会导致构造类的 name 发生改变，所以改成 instanceof 判断
Closed #812
=> fix: fix switch panels between problem and output

src/common/event/__tests__/eventEmitter.test.ts, src/common/event/eventEmitter.ts, website/docs/advanced/event.md, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/advanced/event.md
=> feat: support stop event emit

src/model/workbench/layout.ts, src/services/__tests__/layoutService.test.ts, src/services/workbench/layoutService.ts, src/workbench/__tests__/workbench.test.tsx, src/workbench/editor/__tests__/__snapshots__/editor.test.tsx.snap, src/workbench/editor/__tests__/editor.test.tsx, src/workbench/editor/editor.tsx, stories/extensions/extend-panel/index.tsx
- 支持在 layoutService 中改变 editorGroup 的方向
=> feat: support to set the direction of editor group

src/components/collapse/index.tsx, src/components/collapse/style.scss, src/extensions/github-plus-theme-master/themes/github-plus-theme.json
- 修复 collapse 组件丢失打开动画的问题
- 修复 collapse header 在打开和关闭的情况下会出现抖动的问题
Closed #825
=> fix: fix lost open animation of collapse

src/controller/editor.tsx, src/extensions/editor/index.ts, src/extensions/index.ts, stories/extensions/test/index.tsx
- 修复无法在关闭 tab 之前插入 confirm 的问题
把 controller 里的默认行为放到 default extensions 里，支持用户通过 event 阻止事件链传递
=> fix: can't prevent close tab with confirm

src/services/instanceService.tsx
- 修复在某些情况下无法添加 headerBar 的问题
Closed #829
=> fix: adjust the order of controller

src/components/contextView/index.tsx, src/components/dropdown/index.tsx, src/components/index.ts, src/provider/__tests__/__snapshots__/molecule.test.tsx.snap, src/workbench/__tests__/__snapshots__/workbench.test.tsx.snap, src/workbench/activityBar/activityBar.tsx, src/workbench/activityBar/activityBarItem.tsx, src/workbench/sidebar/explore/folderTree.tsx
- 优化 ContextView 的控制台警告
Closed #830
=> fix: remove contextView warning in console

src/components/contextMenu/index.tsx, src/components/tree/index.tsx, src/workbench/problems/__tests__/paneView.test.tsx, src/workbench/problems/paneView/index.tsx, src/workbench/sidebar/__tests__/searchPanel.test.tsx, src/workbench/sidebar/explore/folderTree.tsx, src/workbench/sidebar/search/searchTree.tsx
- 修复 folderTree 的 Input 右键菜单的问题
前：
后：
确保 Input 的 onContextMenu 不会被 prevenDefault，同时需要 useContextMenu 不会被子元素触发
Closed #837
=> refactor: folderTree'input support default contextmenu

src/controller/__tests__/layout.test.ts, src/controller/layout.ts, src/model/workbench/layout.ts, src/provider/create.ts, src/services/__tests__/layoutService.test.ts, src/services/instanceService.tsx, src/services/workbench/layoutService.ts, src/workbench/workbench.tsx, stories/workbench/0-Workbench.stories.tsx
Refactor the initial logic of `monacoService`. the initWorkspace method depends on the `container` property of `layoutService`,  but the `container` should be set after the `Workbench` component is mounted. 
Fixes #846 
-   the `layoutService` supports [onWorkbenchDidMount](https://github.com/DTStack/molecule/commit/8f4d9aa9c397046a0b56bd89c9027e4bc688d15d) event
-   [Init workspace after workbench did mount](https://github.com/DTStack/molecule/commit/73cbe3864569210d9680ad33e8584489aebc58c4)
=> fix: get container after Workbench is mounted

src/client/components/tree/index.scss, src/client/components/tree/index.tsx, src/client/components/tree/treeNode.tsx, src/extensions/folderTree/index.ts, src/models/folderTree.ts, src/services/folderTree.ts
优化folderTree节点的缩进
优化folderTree缩进线条的交互与展示
folderTree添加onCurrentChange事件
优化前：
优化后：
- 激活节点为文件（叶子节点）：
所有兄弟节点的最后一个缩进线条，以及兄弟节点下所有后代节点的同一缩进位置线条激活
- 激活节点为文件夹：
文件夹展开时，所有后代节点的同一缩进位置线条激活
文件夹关闭时，当前文件夹的父节点下所有后代节点的同一缩进位置线条激活
=> feat(folderTree): support to show active indent line

src/services/workbench/__tests__/editorService.test.tsx, src/services/workbench/editorService.ts
There exists a infinite loop.Determine whether to update the modal value based on comparing the passed-in value and the modal value.
https://github.com/DTStack/molecule/issues/881
=> fix: compare incoming value with modal's value
